**PANDAS**

Import Pandas

In [ ]:
import pandas as pd

**Series Data**

In [ ]:
age = pd.Series([50,30,40,60])
print(age)

0    50
1    30
2    40
3    60
dtype: int64

**Data Frame**

In [ ]:
age = pd.Series([50,30,40,60])
date=pd.DataFrame(age)
print(date)

data={
      "product":['laptop','Mobile',"Mouse"],
      "Price":[20000,15000,200]
}

pd.DataFrame(data)

    0
0  50
1  30
2  40
3  60

  product  Price
0  laptop  20000
1  Mobile  15000
2   Mouse    200

**Data Load**

In [ ]:
df = pd.read_csv('/content/student_sql_python_practice_100.csv')

In [ ]:
df.head()

,Student_ID,Name,Gender,Age,Department,Semester,Email,Phone,City,Admission_Date,GPA,Attendance_Percent,Total_Credit,Status
0,STU001,Tania Hossain,Male,22,CSE,4,tania.hossain1@example.com,1728728463,Gazipur,1/25/2026,2.27,73.6,60,Active
1,STU002,Fahim Islam,Male,21,Law,7,fahim.islam2@example.com,1739587039,Khulna,7/27/2024,3.64,55.3,105,Graduated
2,STU003,Mahin Chowdhury,Female,20,CSE,6,mahin.chowdhury3@example.com,1723718431,Gazipur,2/21/2025,2.28,92.3,96,Active
3,STU004,Faria Ahmed,Female,19,English,2,faria.ahmed4@example.com,1784093639,Cumilla,1/14/2025,3.20,86.0,30,Graduated
4,STU005,Rafi Khan,Male,21,BBA,7,rafi.khan5@example.com,1747308985,Khulna,1/21/2025,2.41,70.6,111,Active

In [ ]:
df.tail()

,Student_ID,Name,Gender,Age,Department,Semester,Email,Phone,City,Admission_Date,GPA,Attendance_Percent,Total_Credit,Status
95,STU096,Raisa Rahman,Male,22,CSE,3,raisa.rahman96@example.com,1782506491,Cumilla,12/28/2023,2.31,93.1,45,Active
96,STU097,Siam Islam,Female,18,CSE,5,siam.islam97@example.com,1717032877,Narayanganj,5/16/2025,3.10,87.8,78,Active
97,STU098,Raisa Chowdhury,Male,25,Law,4,raisa.chowdhury98@example.com,1792558242,Dhaka,12/7/2025,2.67,83.3,60,Active
98,STU099,Jubayer Akter,Female,19,English,8,jubayer.akter99@example.com,1719863756,Gazipur,10/25/2024,3.26,57.9,123,Probation
99,STU100,Tania Hasan,Female,24,Law,5,tania.hasan100@example.com,1770896652,Mymensingh,6/4/2025,2.29,85.9,81,Graduated

In [ ]:
"total_record:", df.shape[0]

('total_record:', 100)

In [ ]:
print("total_record:", df.shape[0])

total_record: 100

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          100 non-null    object
 1   Name                100 non-null    object
 2   Gender              100 non-null    object
 3   Age                 100 non-null    int64
 4   Department          100 non-null    object
 5   Semester            100 non-null    int64
 6   Email               100 non-null    object
 7   Phone               100 non-null    int64
 8   City                100 non-null    object
 9   Admission_Date      100 non-null    object
 10  GPA                 100 non-null    float64
 11  Attendance_Percent  100 non-null    float64
 12  Total_Credit        100 non-null    int64
 13  Status              100 non-null    object
dtypes: float64(2), int64(4), object(8)
memory usage: 11.1+ KB

In [ ]:
df.describe()

,Age,Semester,Phone,GPA,Attendance_Percent,Total_Credit
count,100.000000,100.00000,1.000000e+02,100.00000,100.000000,100.000000
mean,21.530000,4.90000,1.755629e+09,3.04630,77.687000,76.380000
std,2.354686,2.20422,2.528485e+07,0.56514,12.683742,33.265926
min,18.000000,1.00000,1.713278e+09,2.10000,55.100000,15.000000
25%,19.000000,3.00000,1.737516e+09,2.54750,67.275000,45.000000
50%,22.000000,5.00000,1.748928e+09,3.09000,79.350000,78.000000
75%,23.000000,7.00000,1.779103e+09,3.52250,88.000000,108.000000
max,25.000000,8.00000,1.799152e+09,3.97000,97.600000,126.000000

In [ ]:
df.isnull()

,Student_ID,Name,Gender,Age,Department,Semester,Email,Phone,City,Admission_Date,GPA,Attendance_Percent,Total_Credit,Status
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

Student_ID            0
Name                  0
Gender                0
Age                   0
Department            0
Semester              0
Email                 0
Phone                 0
City                  0
Admission_Date        0
GPA                   0
Attendance_Percent    0
Total_Credit          0
Status                0
dtype: int64

In [ ]:
df.columns

Index(['Student_ID', 'Name', 'Gender', 'Age', 'Department', 'Semester',
       'Email', 'Phone', 'City', 'Admission_Date', 'GPA', 'Attendance_Percent',
       'Total_Credit', 'Status'],
      dtype='object')

In [ ]:
df["GPA"].mean()

np.float64(3.046300000000001)

In [ ]:
print("Average_GPA: " , df['GPA'].mean() )

Average_GPA:  3.046300000000001